Repository DotNetAnalyzers/StyleCopAnalyzers, pull requests merged in 2018-05, with the labels that each got.

#2664 Update StyleCopTester
  NuGet.config
  StyleCop.Analyzers/StyleCopTester/App.config
  StyleCop.Analyzers/StyleCopTester/Program.cs
  StyleCop.Analyzers/StyleCopTester/Properties/launchSettings.json
  StyleCop.Analyzers/StyleCopTester/StyleCopTester.csproj
Labels: code review

#2667 Restrict the instance context of SA1101 to accessors
  StyleCop.Analyzers/StyleCop.Analyzers.Test/ReadabilityRules/SA1101UnitTests.cs
  StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1101PrefixLocalCallsWithThis.cs
Labels: code review

#2668 Support empty lines in header comments
  StyleCop.Analyzers/StyleCop.Analyzers.CodeFixes/DocumentationRules/FileHeaderCodeFixProvider.cs
  StyleCop.Analyzers/StyleCop.Analyzers.Test/DocumentationRules/NoXmlFileHeaderUnitTests.cs
Labels: code review

#2670 Include CS1712 in the documentation for SA0001
  documentation/SA0001.md
Labels: code review

#2669 Consolidate diagnostic and code fix tests for SA1121
  StyleCop.Analyzers/StyleCop.Analyzers.Test/ReadabilityRules/SA1121UnitTests.cs
Labels: code review

#2293 Improves SA1642/SA1643 codefix when working with default Visual Studi…
  StyleCop.Analyzers/StyleCop.Analyzers.CodeFixes/DocumentationRules/SA1642SA1643CodeFixProvider.cs
  StyleCop.Analyzers/StyleCop.Analyzers.Test/DocumentationRules/SA1642UnitTests.cs
  StyleCop.Analyzers/StyleCop.Analyzers.Test/DocumentationRules/SA1643UnitTests.cs
Labels: code review, enhancement

#2676 Update SA1131 to support default literal expressions
  StyleCop.Analyzers/StyleCop.Analyzers.Test.CSharp7/ReadabilityRules/SA1131CSharp7UnitTests.cs
  StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1131UseReadableConditions.cs
Labels: code review

#2695 Improve SA1642 code fix handling of empty lines
  StyleCop.Analyzers/StyleCop.Analyzers.CodeFixes/DocumentationRules/SA1642SA1643CodeFixProvider.cs
  StyleCop.Analyzers/StyleCop.Analyzers.Test/DocumentationRules/SA1642UnitTests.cs
  StyleCop.Analyzers/StyleCop.Analyzers.Test/DocumentationRules/SA1643UnitTests.cs
Labels: code review

#2697 Additional test cases for SA1135
  StyleCop.Analyzers/StyleCop.Analyzers.Test/ReadabilityRules/SA1135UnitTests.cs
Labels: code review

#2707 Added SA1135 to ReadabilityRules.md
  documentation/ReadabilityRules.md
Labels: documentation

#2708 Fixed issue where SA1002 was reported when a semicolon is the last ch…
  StyleCop.Analyzers/StyleCop.Analyzers.Test/SpacingRules/SA1002UnitTests.cs
  StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1002SemicolonsMustBeSpacedCorrectly.cs
Labels: code review
